travis:
  secure:
    BINSTAR_TOKEN: kci27e68GVdxjavDvfDykdpPGU924eXcBIDLcIePqS84m1LCXH4F9k0w39pRi5ITjUCZLZPkzI7bSMh9hQ1B20BPHjL0fHttIWaPAq5DsFAUnzYEQz9PKcwJpyPvaB4ax7YkSbXcUlU6Eysod8/xDNqueLnL3Q12lyO0KDIn3uhoA7HSDqL5jlPtdhbexw6vRfARf4xJYQd32C26bpsI4e0lXorpU9+GCqNOzCP4S1j/2oaqi8O1vicy6sjX34D7+OBh2cC1HUaMTqIfzBpBjPL/yMemkqDPjqN1bftDyOpRQ38mSS7InNtJwXOoCSW5w1H9DXUJqEMBh/y1f29sBT+3D75FL0bNX9AfGo0gWt/rOAgBPVsQyZuLS+Ze8QvadnImOT23XEmNzJezULsvQlYE6eTXRLl30MuGKUkhS49C+3XegLoJE1ChV1lKzmBzS5h3Ejh7tO+nBgwhmZ1B8NtIGCmcbpYuB2OCDvDACgoqTlLcyAawO1Cdfj23+GfMzrV7/PvxgnVv+bgJNQMwS4W6h4iHRZAl+xCWxtHHv8LwhTfohQc2oR5X3/XwhD4tqC3pIOmGnCjUw0ZH3IXr//mP5WtmzxMJfzTfZmpZ/wsv/qxmorQFgfp/vyFoeIg6IqU1pa/jiJPV273AFLRSSx3PBS5yH1TRgj09Brehb8c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
